# Generated by Django 4.2.4 on 2023-09-20 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("complex", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="type_master",
            field=models.ForeignKey(
                default=0,
                help_text="type_master character",
                limit_choices_to={"key": "character"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="character",
                to="complex.type_master",
                verbose_name="分類",
            ),
        ),
        migrations.AlterField(
            model_name="comic",
            name="isbn",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="ISBN13"
            ),
        ),
        migrations.AlterField(
            model_name="comic",
            name="number",
            field=models.PositiveIntegerField(
                default=1, help_text="第n巻 入力するのは数字のみ", verbose_name="巻数"
            ),
        ),
        migrations.AlterField(
            model_name="comic",
            name="series",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="comic",
                to="complex.series",
            ),
        ),
        migrations.AlterField(
            model_name="comic",
            name="title",
            field=models.CharField(
                default="no title",
                help_text="例：ざつ旅-That's Journey- 1。※巻数の表記は作品毎に呼び方のバリエーションがある",
                max_length=255,
                verbose_name="各巻タイトル",
            ),
        ),
        migrations.AlterField(
            model_name="fragment",
            name="place",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fragment",
                to="complex.place",
            ),
        ),
        migrations.AlterField(
            model_name="fragment",
            name="story",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fragment",
                to="complex.story",
            ),
        ),
        migrations.AlterField(
            model_name="fragment",
            name="title",
            field=models.CharField(
                default="no title", max_length=255, verbose_name="名前"
            ),
        ),
        migrations.AlterField(
            model_name="fragment",
            name="type_master",
            field=models.ForeignKey(
                default=0,
                help_text="type_master fragment",
                limit_choices_to={"key": "fragment"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="fragment",
                to="complex.type_master",
                verbose_name="分類",
            ),
        ),
        migrations.AlterField(
            model_name="fragment",
            name="web_comic",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fragment",
                to="complex.web_comic",
            ),
        ),
        migrations.AlterField(
            model_name="journey",
            name="type_master",
            field=models.ForeignKey(
                default=0,
                help_text="type_master journey",
                limit_choices_to={"key": "journey"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="journey",
                to="complex.type_master",
                verbose_name="分類",
            ),
        ),
        migrations.AlterField(
            model_name="magazine",
            name="title",
            field=models.CharField(
                default="no title",
                help_text="雑誌のタイトル 例：電撃マオウ 2020年1月号",
                max_length=255,
                verbose_name="タイトル",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="type_master",
            field=models.ForeignKey(
                default=0,
                help_text="type_master person",
                limit_choices_to={"key": "person"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="person",
                to="complex.type_master",
                verbose_name="分類",
            ),
        ),
        migrations.AlterField(
            model_name="photo",
            name="person",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="photo",
                to="complex.person",
            ),
        ),
        migrations.AlterField(
            model_name="photo",
            name="step",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="photo",
                to="complex.step",
            ),
        ),
        migrations.AlterField(
            model_name="photo",
            name="title",
            field=models.CharField(
                blank=True, default="no titile", max_length=255, verbose_name="タイトル"
            ),
        ),
        migrations.AlterField(
            model_name="photo",
            name="type_master",
            field=models.ForeignKey(
                default=0,
                help_text="type_master photo",
                limit_choices_to={"key": "photo"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="photo",
                to="complex.type_master",
                verbose_name="分類",
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="venue",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="place",
                to="complex.venue",
            ),
        ),
        migrations.AlterField(
            model_name="route",
            name="type_master",
            field=models.ForeignKey(
                default=0,
                help_text="type_master route",
                limit_choices_to={"key": "route"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="route",
                to="complex.type_master",
                verbose_name="分類",
            ),
        ),
        migrations.AlterField(
            model_name="scene",
            name="place",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="scene",
                to="complex.place",
            ),
        ),
        migrations.AlterField(
            model_name="scene",
            name="story",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="scene",
                to="complex.story",
            ),
        ),
        migrations.AlterField(
            model_name="scene",
            name="type_master",
            field=models.ForeignKey(
                default=0,
                help_text="type_master scene",
                limit_choices_to={"key": "scene"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="scene",
                to="complex.type_master",
                verbose_name="分類",
            ),
        ),
        migrations.AlterField(
            model_name="series",
            name="author",
            field=models.CharField(
                default="no author",
                help_text="著者複数名の場合は、代表者をカンマ区切りで列挙する",
                max_length=255,
                verbose_name="著者名",
            ),
        ),
        migrations.AlterField(
            model_name="series",
            name="label",
            field=models.CharField(
                blank=True,
                default="",
                help_text="コミック・シリーズのレーベル名称 例：電撃コミックスNEXT",
                max_length=255,
                verbose_name="レーベル",
            ),
        ),
        migrations.AlterField(
            model_name="series",
            name="rel_series_id",
            field=models.PositiveIntegerField(
                blank=True, help_text="空欄のままでOK", null=True, verbose_name="関係シリーズ"
            ),
        ),
        migrations.AlterField(
            model_name="series",
            name="title",
            field=models.CharField(
                default="no title",
                help_text="正確な作品の名称",
                max_length=255,
                verbose_name="作品名",
            ),
        ),
        migrations.AlterField(
            model_name="step",
            name="place",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="step",
                to="complex.place",
            ),
        ),
        migrations.AlterField(
            model_name="step",
            name="route",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="step",
                to="complex.route",
            ),
        ),
        migrations.AlterField(
            model_name="story",
            name="camera_center_place",
            field=models.ForeignKey(
                help_text="place story このストーリーに登場する主な地点をすべて包含するような範囲(四角形)の中心",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="camera_center_place",
                to="complex.place",
                verbose_name="(領域設定用)",
            ),
        ),
        migrations.AlterField(
            model_name="story",
            name="comic",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="story",
                to="complex.comic",
            ),
        ),
        migrations.AlterField(
            model_name="story",
            name="journey",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="story",
                to="complex.journey",
            ),
        ),
        migrations.AlterField(
            model_name="story",
            name="title",
            field=models.CharField(
                default="no title", max_length=255, verbose_name="単話タイトル"
            ),
        ),
        migrations.AlterField(
            model_name="story",
            name="type_master",
            field=models.ForeignKey(
                default=0,
                help_text="type_master story",
                limit_choices_to={"key": "story"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="story",
                to="complex.type_master",
                verbose_name="分類",
            ),
        ),
        migrations.AlterField(
            model_name="tweet",
            name="person",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tweet",
                to="complex.person",
            ),
        ),
        migrations.AlterField(
            model_name="tweet",
            name="step",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tweet",
                to="complex.step",
            ),
        ),
        migrations.AlterField(
            model_name="tweet",
            name="type_master",
            field=models.ForeignKey(
                default=0,
                help_text="type_master tweet",
                limit_choices_to={"key": "tweet"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tweet",
                to="complex.type_master",
                verbose_name="分類",
            ),
        ),
        migrations.AlterField(
            model_name="type_master",
            name="key",
            field=models.CharField(default="-", max_length=255, verbose_name="属性"),
        ),
        migrations.AlterField(
            model_name="type_master",
            name="name",
            field=models.CharField(
                blank=True, default="🚫", max_length=255, verbose_name="参照名"
            ),
        ),
        migrations.AlterField(
            model_name="type_master",
            name="value",
            field=models.CharField(default="***", max_length=255, verbose_name="値"),
        ),
        migrations.AlterField(
            model_name="venue",
            name="type_master",
            field=models.ForeignKey(
                default=0,
                help_text="type_master venue",
                limit_choices_to={"key": "venue"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="venue",
                to="complex.type_master",
                verbose_name="分類",
            ),
        ),
        migrations.AlterField(
            model_name="web_comic",
            name="story",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="web_comic",
                to="complex.story",
            ),
        ),
        migrations.AlterField(
            model_name="web_comic",
            name="title",
            field=models.CharField(
                default="no title", max_length=255, verbose_name="各話の名前"
            ),
        ),
        migrations.AddConstraint(
            model_name="comic",
            constraint=models.UniqueConstraint(
                fields=("title", "isbn"), name="unique_comic"
            ),
        ),
        migrations.AddConstraint(
            model_name="fragment",
            constraint=models.UniqueConstraint(
                fields=("title",), name="unique_fragment"
            ),
        ),
        migrations.AddConstraint(
            model_name="magazine",
            constraint=models.UniqueConstraint(
                fields=("title",), name="unique_magazine"
            ),
        ),
        migrations.AddConstraint(
            model_name="series",
            constraint=models.UniqueConstraint(
                fields=("title", "author", "label"), name="unique_series"
            ),
        ),
        migrations.AddConstraint(
            model_name="type_master",
            constraint=models.UniqueConstraint(
                fields=("key", "value"), name="unique_type_master"
            ),
        ),
        migrations.AddConstraint(
            model_name="web_comic",
            constraint=models.UniqueConstraint(
                fields=("title",), name="unique_web_comic"
            ),
        ),
    ]
