# Generated by Django 4.2.4 on 2023-09-25 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("complex", "0003_alter_magazine_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="step",
            name="place",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="step",
                to="complex.place",
            ),
        ),
    ]
